version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # JavaScript/Node.js (npm/yarn dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Python (pip dependencies)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Ruby (bundler dependencies)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  # Java (maven dependencies)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  # Java (gradle dependencies)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # PHP (composer dependencies)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # .NET (nuget dependencies)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Rust (cargo dependencies)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Elixir (mix dependencies)
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
