**dependabot.yml**
```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      - daily
    ignore:
      - jrichy1/jrichy1@^1.0.0
      - jrichy1/jrichy1@^2.0.0
    versioning:
      - type: semver
        prefix: v
        regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$

  - package-ecosystem: npm
    directory: /
    schedule:
      - daily
    ignore:
      - jrichy1/jrichy1@^3.0.0
    versioning:
      - type: semver
        prefix: v
        regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$

  - package-ecosystem: npm
    directory: /
    schedule:
      - daily
    ignore:
      - jrichy1/jrichy1@^1.1.0
      - jrichy1/jrichy1@^1.2.0
      - jrichy1/jrichy1@^1.3.0
    versioning:
      - type: semver
        prefix: v
        regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$

  - package-ecosystem: npm
    directory: /
    schedule:
      - daily
    ignore:
      - jrichy1/jrichy1@^2.1.0
      - jrichy1/jrichy1@^2.2.0
    versioning:
      - type: semver
        prefix: v
        regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$

  - package-ecosystem: npm
    directory: /
    schedule:
      - daily
    ignore:
      - jrichy1/jrichy1@^3.1.0
      - jrichy1/jrichy1@^3.2.0
    versioning:
      - type: semver
        prefix: v
        regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$
```
