version: 2
versioning:
  type: semver
  prefix: v
  regex: ^v(\d+(?:\.\d+)*)(?:\.(\d+)(?:\.(\d+))?)?$
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      - interval: weekly
    ignore:
      - jrichy1/jrichy1@^1.0.0
      - jrichy1/jrichy1@^2.0.0
      - jrichy1/jrichy1@^3.0.0
      - jrichy1/jrichy1@^1.1.0
      - jrichy1/jrichy1@^1.2.0
      - jrichy1/jrichy1@^1.3.0
      - jrichy1/jrichy1@^2.1.0
      - jrichy1/jrichy1@^2.2.0
      - jrichy1/jrichy1@^3.1.0
      - jrichy1/jrichy1@^3.2.0

  - package-ecosystem: github-actions
    directory: /
    schedule:
      - interval: weekly
    ignore:
      - dependency-name: actions/checkout
        versions: ["v4"]
      - dependency-name: actions/configure-pages
        versions: ["v5"]
      - dependency-name: actions/jekyll-build-pages
        versions: ["v1"]
      - dependency-name: actions/upload-pages-artifact
        versions: ["v3"]
      - dependency-name: actions/deploy-pages
        versions: ["v4"]

  - package-ecosystem: pip
    directory: /
    schedule:
      - interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      - interval: weekly
